#!/usr/bin/env python3
"""
Pink Oregon Trail — Historical Photos Embedder (v2.4 — folder-first)

This script reads JPG/PNG files from a `historical_photos/` folder at the
project root and embeds them as base64 inside `pink_oregon_trail.html`,
which then displays real photographs at the 9 historical landmarks.

Photos NOT supplied locally fall back to the daguerreotype-style SVG
illustrations baked into the game. You can supply 0, 1, or all 9 — any
combination works.

WHY FOLDER-BASED INSTEAD OF URL-BASED:
The previous v2.3 fetcher tried to download photos from Library of Congress
URLs at runtime. Several of those URLs were unstable and the script
hard-failed when too few succeeded. This version reads from a local folder
you control, which is reliable, debuggable, and lets you choose exactly
which images you want.

USAGE:

  1. Create a folder called `historical_photos/` next to pink_oregon_trail.html
  2. Drop JPG or PNG files into it, named with the landmark IDs:
       - fort_laramie.jpg
       - chimney_rock.jpg
       - independence_rock.jpg
       - soda_springs.jpg
       - south_pass.jpg
       - fort_bridger.jpg
       - whitman_mission.jpg
       - the_dalles.jpg
       - oregon_city.jpg
  3. Run: `python fetch_historical_photos.py`
  4. Open pink_oregon_trail.html — your photos appear at the matching landmarks.

WHERE TO FIND PUBLIC-DOMAIN IMAGES:

  - Library of Congress — https://www.loc.gov/photos
    Search for the location name. Click an image. Click "Download." Pick "JPEG."
    Almost everything from before 1928 is public domain in the US.

  - Wikimedia Commons — https://commons.wikimedia.org
    Search the location name + "historical." Filter by "Public domain."
    Right-click an image, "Save Image As..."

  - Oregon-California Trails Association — https://octa-trails.org

  - National Park Service — many parks have photo archives

If a landmark has no surviving period photograph (Whitman Mission was destroyed
in 1847 — most pre-photography images don't exist), use any historically-themed
illustration, OR just leave that file out and the SVG fallback is used.

REQUIREMENTS:
  Python 3.8+ and Pillow. Install Pillow with: pip install pillow
"""

import argparse
import base64
import io
import re
import sys
from pathlib import Path

# The 9 landmark IDs the game knows about. The script looks for files
# named "<id>.jpg", "<id>.jpeg", or "<id>.png" in the photos folder.
LANDMARK_IDS = [
    'fort_laramie',
    'chimney_rock',
    'independence_rock',
    'soda_springs',
    'south_pass',
    'fort_bridger',
    'whitman_mission',
    'the_dalles',
    'oregon_city',
]

ACCEPTED_EXTENSIONS = ('.jpg', '.jpeg', '.png')

# Maximum dimensions when resizing for embedding (preserves aspect ratio)
MAX_WIDTH = 600
MAX_HEIGHT = 460
JPEG_QUALITY = 80


def log(msg, level='info'):
    prefix = {'info': '   ', 'ok': ' + ', 'warn': ' ! ', 'err': ' x '}.get(level, '   ')
    print(prefix + msg)


def find_local_file(folder, landmark_id):
    """Look for landmark_id.jpg / .jpeg / .png in folder. Return Path or None."""
    if not folder.exists():
        return None
    for ext in ACCEPTED_EXTENSIONS:
        candidate = folder / (landmark_id + ext)
        if candidate.exists() and candidate.is_file():
            return candidate
    return None


def encode_image(path):
    """Load image, downscale to fit MAX_WIDTH x MAX_HEIGHT, return base64 string."""
    try:
        from PIL import Image
    except ImportError:
        log('Pillow is required. Install with: pip install pillow', 'err')
        sys.exit(1)
    try:
        img = Image.open(path).convert('RGB')
        original_size = img.size
        img.thumbnail((MAX_WIDTH, MAX_HEIGHT), Image.LANCZOS)
        buf = io.BytesIO()
        img.save(buf, format='JPEG', quality=JPEG_QUALITY, optimize=True)
        encoded = base64.b64encode(buf.getvalue()).decode('ascii')
        return {
            'b64': encoded,
            'original_size': original_size,
            'embedded_size': img.size,
            'kb': len(encoded) // 1024,
        }
    except Exception as e:
        log('    failed to process ' + path.name + ': ' + str(e), 'err')
        return None


def patch_html(html_path, photos):
    """Insert or replace the historical-photos-override <script> block.

    photos: dict of landmark_id -> base64 string (only successful entries).
    Always writes a block, even if empty, so the consumer code reliably finds
    window.HISTORICAL_PHOTOS_OVERRIDE.
    """
    if not html_path.exists():
        log('HTML file not found: ' + str(html_path), 'err')
        sys.exit(1)
    html = html_path.read_text(encoding='utf-8')
    block_lines = ['  window.HISTORICAL_PHOTOS_OVERRIDE = {']
    for lid in LANDMARK_IDS:
        if lid in photos:
            block_lines.append('    ' + lid + ': "' + photos[lid] + '",')
    block_lines.append('  };')
    new_block = (
        '<script id="historical-photos-override">\n'
        '  // Generated by fetch_historical_photos.py - DO NOT EDIT BY HAND.\n'
        '  // Re-run the script to refresh. To remove: delete this <script> block\n'
        '  // OR delete every file in historical_photos/ and re-run.\n'
        + '\n'.join(block_lines) + '\n'
        '</script>\n'
    )
    pattern = re.compile(
        r'<script id="historical-photos-override">.*?</script>\s*',
        re.DOTALL,
    )
    if pattern.search(html):
        html = pattern.sub(new_block, html, count=1)
        log('replaced existing override block in HTML', 'ok')
    else:
        if '</body>' not in html:
            log('could not find </body> in HTML - file may be malformed', 'err')
            sys.exit(1)
        html = html.replace('</body>', new_block + '</body>', 1)
        log('inserted override block before </body>', 'ok')
    html_path.write_text(html, encoding='utf-8')
    size_kb = html_path.stat().st_size // 1024
    log('wrote pink_oregon_trail.html (' + str(size_kb) + ' KB)', 'ok')


def main():
    parser = argparse.ArgumentParser(
        description='Embed local historical photos into pink_oregon_trail.html.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        '--html', default='pink_oregon_trail.html',
        help='Path to pink_oregon_trail.html (default: %(default)s)',
    )
    parser.add_argument(
        '--photos', default='historical_photos',
        help='Path to the photos folder (default: %(default)s)',
    )
    args = parser.parse_args()

    html_path = Path(args.html).resolve()
    photos_dir = Path(args.photos).resolve()

    print('=' * 64)
    print('Pink Oregon Trail - Historical Photos Embedder (v2.4)')
    print('=' * 64)
    print('HTML target:    ' + str(html_path))
    print('Photos folder:  ' + str(photos_dir))
    print()

    if not photos_dir.exists():
        log('photos folder does not exist - creating it', 'warn')
        photos_dir.mkdir(parents=True, exist_ok=True)
        log('created ' + str(photos_dir) + '. Drop JPG/PNG files in there named like:', 'info')
        for lid in LANDMARK_IDS:
            log('    ' + lid + '.jpg', 'info')
        log('Then re-run this script.', 'info')
        patch_html(html_path, {})
        log('wrote empty override block. Game uses SVG fallbacks for all 9 landmarks.', 'ok')
        return

    photos = {}
    print('Scanning photos folder...')
    print()
    for lid in LANDMARK_IDS:
        local_file = find_local_file(photos_dir, lid)
        if local_file is None:
            log(lid.ljust(20) + ' no file -> SVG fallback', 'info')
            continue
        log(lid.ljust(20) + ' found ' + local_file.name, 'ok')
        result = encode_image(local_file)
        if result is None:
            log(lid.ljust(20) + ' encode failed -> SVG fallback', 'warn')
            continue
        photos[lid] = result['b64']
        log('    encoded ' + str(result['kb']) + ' KB base64 (' +
            str(result['embedded_size'][0]) + 'x' + str(result['embedded_size'][1]) + ')', 'info')

    print()
    log('embedded ' + str(len(photos)) + ' of ' + str(len(LANDMARK_IDS)) + ' landmarks', 'ok')
    if len(photos) == 0:
        log('no photos to embed. Add JPG/PNG files to ' + str(photos_dir) + ' named:', 'warn')
        for lid in LANDMARK_IDS:
            log('    ' + lid + '.jpg (or .jpeg or .png)', 'info')
    print()
    patch_html(html_path, photos)
    print()
    log('Done. Open pink_oregon_trail.html in a browser to verify.', 'ok')
    log('Re-run this script anytime you add or remove photos.', 'info')


if __name__ == '__main__':
    main()
